import { createClient } from "@supabase/supabase-js";
import type { Database } from "./supabase"; // Type definitions for your database schema (auto-generated by Supabase)

// Load Supabase credentials from environment variables.
// These should be defined in your Vite `.env` file.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Create a single Supabase client instance for the entire app.
// The generic type <Database> ensures full TypeScript support for table names, columns, and queries.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
